language: generic

sudo: required

services:
  - docker

before_script:
  - export STENCILA_TAG=$(date --utc --iso-8601)

script:
  - ./.build/build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then ./.build/push.sh; fi
