language: generic

sudo: required

services:
  - docker

before_script:
  - export STENCILA_TAG=$(date --utc --iso-8601)
  - export STENCILA_IMAGES=$(find -mindepth 1 -maxdepth 1 -type d -not -name '\.*' -printf '%P\n')

script:
  - ./.build/build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then ./.build/push.sh; fi
