language: nix

services:
  - docker

install:
  - make setup

script:
  # Currently, adding these causes the build to exceed time limit (50mins)
  #- make base/node/
  #- make base/py/
  #- make base/r/
  - make base/
  - make test
