# This file has been generated by node2nix 1.4.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "machine-13.0.0-24" = {
      name = "machine";
      packageName = "machine";
      version = "13.0.0-24";
      src = fetchurl {
        url = "https://registry.npmjs.org/machine/-/machine-13.0.0-24.tgz";
        sha512 = "3pml8qj4h101iha3n2smfxxsbdmwcx4dl9v8m4j4b425l3kk1kippl2vhka6x15q4qmc1h0w5wf1l5rz89hp7f1jvj060p5n50wr21k";
      };
    };
    "machinepack-arrays-git://github.com/treelinehq/machinepack-arrays.git#fcb0f382ef9b5c546bf1c204bae13dc3bf2b4985" = {
      name = "machinepack-arrays";
      packageName = "machinepack-arrays";
      version = "5.4.0";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-arrays.git";
        rev = "fcb0f382ef9b5c546bf1c204bae13dc3bf2b4985";
        sha256 = "a7e2bc7e55ac6ea6885c76b9177dd1df05007f13907ae96dbeef25fb896d744d";
      };
    };
    "machinepack-booleans-git://github.com/treelinehq/machinepack-booleans.git#ae639e06ca108fb930650ffa5b6546f3b8e596de" = {
      name = "machinepack-booleans";
      packageName = "machinepack-booleans";
      version = "0.1.1";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-booleans.git";
        rev = "ae639e06ca108fb930650ffa5b6546f3b8e596de";
        sha256 = "d867bed26dafcd3e9bb89fbf96bab69993369427bfae4e16efbdf3227f8c8186";
      };
    };
    "machinepack-console-git://github.com/treelinehq/machinepack-console.git#ec09bcffcb89a446b3d3043b897094c266effeff" = {
      name = "machinepack-console";
      packageName = "machinepack-console";
      version = "0.2.0";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-console.git";
        rev = "ec09bcffcb89a446b3d3043b897094c266effeff";
        sha256 = "d5a627952973a3305945a2477243b289f20874a7aeab76e8f37aa75ec6f9da9b";
      };
    };
    "machinepack-datetime-git://github.com/sgress454/machinepack-datetime.git#7e4cb42fdd17f8e4eb7186579f6116282cc484cd" = {
      name = "machinepack-datetime";
      packageName = "machinepack-datetime";
      version = "1.4.0";
      src = fetchgit {
        url = "git://github.com/sgress454/machinepack-datetime.git";
        rev = "7e4cb42fdd17f8e4eb7186579f6116282cc484cd";
        sha256 = "eaf144f62ce7df918d3b16199b06044d47ebb7c5e39398603e82e3d19e018f68";
      };
    };
    "machinepack-dictionaries-git://github.com/treelinehq/machinepack-dictionaries.git#060809c406ace7d276027bc17a9abb6371c7aaa1" = {
      name = "machinepack-dictionaries";
      packageName = "machinepack-dictionaries";
      version = "2.2.0";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-dictionaries.git";
        rev = "060809c406ace7d276027bc17a9abb6371c7aaa1";
        sha256 = "a2c37ac28955ca0a0940cd1d345522273c53c13059f91431a0e178d7be1d4eab";
      };
    };
    "machinepack-emailaddresses-git://github.com/mikermcneil/machinepack-emailaddresses.git#f88649f4acfe428d31641e2abff718d9c86beeaf" = {
      name = "machinepack-emailaddresses";
      packageName = "machinepack-emailaddresses";
      version = "0.4.0";
      src = fetchgit {
        url = "git://github.com/mikermcneil/machinepack-emailaddresses.git";
        rev = "f88649f4acfe428d31641e2abff718d9c86beeaf";
        sha256 = "fc6dc7c529f987ce2d1cb818c6aa9e42ee2af8fd48536784df7b39cf742f1a16";
      };
    };
    "machinepack-fs-git://github.com/mikermcneil/machinepack-fs.git#2a68adb3837c84b3ed80fe87463df2a13649fa95" = {
      name = "machinepack-fs";
      packageName = "machinepack-fs";
      version = "9.0.0-0";
      src = fetchgit {
        url = "git://github.com/mikermcneil/machinepack-fs.git";
        rev = "2a68adb3837c84b3ed80fe87463df2a13649fa95";
        sha256 = "5bbff3f3236576641ad89437d5dcb91ea98632a7e5bc54f29be3de02f76a4d42";
      };
    };
    "machinepack-gravatar-git://github.com/irlnathan/machinepack-gravatar.git#de3e6607c59f354871af3b514808fa290838fb55" = {
      name = "machinepack-gravatar";
      packageName = "machinepack-gravatar";
      version = "1.2.0";
      src = fetchgit {
        url = "git://github.com/irlnathan/machinepack-gravatar.git";
        rev = "de3e6607c59f354871af3b514808fa290838fb55";
        sha256 = "fc2533602e874b768be0ec679aa2d83ecdb80155ea63bf8e3bbc63ea3fece67f";
      };
    };
    "machinepack-http-3.0.0" = {
      name = "machinepack-http";
      packageName = "machinepack-http";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/machinepack-http/-/machinepack-http-3.0.0.tgz";
        sha1 = "9d25872104bac24cfedeedd303e63967ae7744d8";
      };
    };
    "machinepack-ifthen-git://github.com/treelinehq/machinepack-ifthen.git#2faacb7c60a1d3f3118df7e585c1e228bc5a5940" = {
      name = "machinepack-ifthen";
      packageName = "machinepack-ifthen";
      version = "1.3.0";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-ifthen.git";
        rev = "2faacb7c60a1d3f3118df7e585c1e228bc5a5940";
        sha256 = "d774be2020d66291b8114207f0049a3e7dc12cedb6ab2836dbc96c2653965cb2";
      };
    };
    "machinepack-json-git://github.com/treelinehq/machinepack-json.git#cb9b172d24d8a5f6a12f3ad63d95d6985fb2bd70" = {
      name = "machinepack-json";
      packageName = "machinepack-json";
      version = "2.0.1";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-json.git";
        rev = "cb9b172d24d8a5f6a12f3ad63d95d6985fb2bd70";
        sha256 = "6fb204cc0f1c7ae4b1a8dcb829f45c6d5b581a7f53161cd86c0c94e915d75faa";
      };
    };
    "machinepack-mailgun-git://github.com/particlebanana/machinepack-mailgun.git#d473ed00e7195297226740b01a87b01e4149a545" = {
      name = "machinepack-mailgun";
      packageName = "machinepack-mailgun";
      version = "0.6.0";
      src = fetchgit {
        url = "git://github.com/particlebanana/machinepack-mailgun.git";
        rev = "d473ed00e7195297226740b01a87b01e4149a545";
        sha256 = "bdf63663f070e011a2983cb4b7bc3c2ccb9e6edbc7debfe0ecf91bb3cf62bff6";
      };
    };
    "machinepack-math-git://github.com/treelinehq/machinepack-math.git#e33233cc2129098b297eafc14c17dcf88f714244" = {
      name = "machinepack-math";
      packageName = "machinepack-math";
      version = "1.2.0";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-math.git";
        rev = "e33233cc2129098b297eafc14c17dcf88f714244";
        sha256 = "44946d78efa47662a74dce17e8904b1d58b9276e9742eda34b239a80ec2fb6de";
      };
    };
    "machinepack-numbers-git://github.com/treelinehq/machinepack-numbers.git#cdbbccef1fa7e6cbc9549b2b70415c7316ebaa79" = {
      name = "machinepack-numbers";
      packageName = "machinepack-numbers";
      version = "0.1.1";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-numbers.git";
        rev = "cdbbccef1fa7e6cbc9549b2b70415c7316ebaa79";
        sha256 = "1d2909c802b551a31b31530edc1f3bc32a4ce7e86f49b1077fd807b7b4957995";
      };
    };
    "machinepack-passwords-git://github.com/mikermcneil/machinepack-passwords.git#a79274800db769840996498f170258c74118bc2d" = {
      name = "machinepack-passwords";
      packageName = "machinepack-passwords";
      version = "2.3.0";
      src = fetchgit {
        url = "git://github.com/mikermcneil/machinepack-passwords.git";
        rev = "a79274800db769840996498f170258c74118bc2d";
        sha256 = "2f4a4b5606f3e3b6559cd56ad0d6db58a3e0b6a417257e5eb9b6e871243a82c9";
      };
    };
    "machinepack-paths-git://github.com/treelinehq/machinepack-paths.git#2d25ec774bbca6e3de00ff4f3b975e6f421f6da4" = {
      name = "machinepack-paths";
      packageName = "machinepack-paths";
      version = "3.0.0-0";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-paths.git";
        rev = "2d25ec774bbca6e3de00ff4f3b975e6f421f6da4";
        sha256 = "65221fc8117c957c770808d9a7926c59b2f8b4122471c750a8c0b0232e3137f6";
      };
    };
    "machinepack-process-git://github.com/treelinehq/machinepack-process.git#4c9fe46cb0f666e88bd5f0e31ffaf5eaaff1639f" = {
      name = "machinepack-process";
      packageName = "machinepack-process";
      version = "3.0.0-4";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-process.git";
        rev = "4c9fe46cb0f666e88bd5f0e31ffaf5eaaff1639f";
        sha256 = "97f69961ed22ec47d1832f2f1f83070da1679bcd36d6072ae5218df1ff6ddd17";
      };
    };
    "machinepack-strings-git://github.com/treelinehq/machinepack-strings.git#6f429144064c573da4d92226b22d4a7a14d22e94" = {
      name = "machinepack-strings";
      packageName = "machinepack-strings";
      version = "5.1.0";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-strings.git";
        rev = "6f429144064c573da4d92226b22d4a7a14d22e94";
        sha256 = "4850459128c213ce34c780203b0017687ba0ca82c05d6a08600364c20a8c37d8";
      };
    };
    "machinepack-urls-git://github.com/mikermcneil/machinepack-urls.git#49388b3bdba5c9a780834c2c5d29d388a1cf4d90" = {
      name = "machinepack-urls";
      packageName = "machinepack-urls";
      version = "6.0.1";
      src = fetchgit {
        url = "git://github.com/mikermcneil/machinepack-urls.git";
        rev = "49388b3bdba5c9a780834c2c5d29d388a1cf4d90";
        sha256 = "246bb78f58e2949210c7801cf66ad035d4dcf3fb1015685bf4cff40bdadd75d5";
      };
    };
    "machinepack-util-git://github.com/treelinehq/machinepack-util.git#d9866079e883e7db185f91284cfab890f3f430f4" = {
      name = "machinepack-util";
      packageName = "machinepack-util";
      version = "7.0.0-2";
      src = fetchgit {
        url = "git://github.com/treelinehq/machinepack-util.git";
        rev = "d9866079e883e7db185f91284cfab890f3f430f4";
        sha256 = "c906db0e1c4387f48ec6aa3ff4162ed83cea0c8c8034b57bb8cf4308c0fde81d";
      };
    };
    "@sailshq/lodash-3.10.2" = {
      name = "_at_sailshq_slash_lodash";
      packageName = "@sailshq/lodash";
      version = "3.10.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sailshq/lodash/-/lodash-3.10.2.tgz";
        sha1 = "1567d47345364c2c2e2077bc113487b1dfe62154";
      };
    };
    "convert-to-ecmascript-compatible-varname-0.1.4" = {
      name = "convert-to-ecmascript-compatible-varname";
      packageName = "convert-to-ecmascript-compatible-varname";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-to-ecmascript-compatible-varname/-/convert-to-ecmascript-compatible-varname-0.1.4.tgz";
        sha1 = "49ff46e96c1d356a91d4b83e5ffe0133c3c8ac14";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "3g1hqsahr1ks2kpvdxrwzr57fj90nnr0hvwwrw8yyyzcv3i11sym8zwibxx67bl1mln0acddrzpkkdjjxnc6n2cm9fazmgzzsl1fzrr";
      };
    };
    "include-all-1.0.8" = {
      name = "include-all";
      packageName = "include-all";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/include-all/-/include-all-1.0.8.tgz";
        sha1 = "e8bb84b057278a22cf944319037d9700c18a4379";
      };
    };
    "rttc-9.8.2" = {
      name = "rttc";
      packageName = "rttc";
      version = "9.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rttc/-/rttc-9.8.2.tgz";
        sha1 = "2337d21d413f4a34fff88177f95eae7edfbd26bf";
      };
    };
    "switchback-2.0.2" = {
      name = "switchback";
      packageName = "switchback";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/switchback/-/switchback-2.0.2.tgz";
        sha1 = "96cf0e0d363b559d0bb7ff21b62a7aa910ec6079";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "lodash-3.10.1" = {
      name = "lodash";
      packageName = "lodash";
      version = "3.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-3.10.1.tgz";
        sha1 = "5bf45e8e49ba4189e17d482789dfd15bd140b7b6";
      };
    };
    "async-0.9.2" = {
      name = "async";
      packageName = "async";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.9.2.tgz";
        sha1 = "aea74d5e61c1f899613bf64bda66d4c78f2fd17d";
      };
    };
    "rttc-8.1.7" = {
      name = "rttc";
      packageName = "rttc";
      version = "8.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/rttc/-/rttc-8.1.7.tgz";
        sha1 = "38392c8e90396de55d81b9f18d1ff60f7443020c";
      };
    };
    "moment-2.15.2" = {
      name = "moment";
      packageName = "moment";
      version = "2.15.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.15.2.tgz";
        sha1 = "1bfdedf6a6e345f322fe956d5df5bd08a8ce84dc";
      };
    };
    "moment-timezone-0.3.1" = {
      name = "moment-timezone";
      packageName = "moment-timezone";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment-timezone/-/moment-timezone-0.3.1.tgz";
        sha1 = "3ef47856b02d53b718a10a5ec2023aa299e07bf5";
      };
    };
    "browserify-transform-machinepack-1.0.3" = {
      name = "browserify-transform-machinepack";
      packageName = "browserify-transform-machinepack";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-transform-machinepack/-/browserify-transform-machinepack-1.0.3.tgz";
        sha1 = "83374310fc83266af9fbcf2f17dee4183d0d88f8";
      };
    };
    "browserify-transform-tools-1.7.0" = {
      name = "browserify-transform-tools";
      packageName = "browserify-transform-tools";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-transform-tools/-/browserify-transform-tools-1.7.0.tgz";
        sha1 = "83e277221f63259bed2e7eb2a283a970a501f4c4";
      };
    };
    "falafel-2.1.0" = {
      name = "falafel";
      packageName = "falafel";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/falafel/-/falafel-2.1.0.tgz";
        sha1 = "96bb17761daba94f46d001738b3cedf3a67fe06c";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "acorn-5.3.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-5.3.0.tgz";
        sha512 = "197zp88clmmxjyvhahqv32kv07q825hf87facxaq8qmvb1swfqnpyy4398dl56sr2fa44f7gjpzzlwy1szqzwww6746y3kmwb6gxs31";
      };
    };
    "foreach-2.0.5" = {
      name = "foreach";
      packageName = "foreach";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz";
        sha1 = "0bee005018aeb260d0a3af3ae658dd0136ec1b99";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "object-keys-1.0.11" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.0.11.tgz";
        sha1 = "c54601778ad560f1142ce0e01bcca8b56d13426d";
      };
    };
    "validator-3.43.0" = {
      name = "validator";
      packageName = "validator";
      version = "3.43.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-3.43.0.tgz";
        sha1 = "96464b992d4196833d97a194bf40b19ff54bae05";
      };
    };
    "fs-extra-0.30.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "0.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-0.30.0.tgz";
        sha1 = "f233ffcc08d4da7d432daa449776989db1df93f0";
      };
    };
    "lodash.isfunction-3.0.8" = {
      name = "lodash.isfunction";
      packageName = "lodash.isfunction";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isfunction/-/lodash.isfunction-3.0.8.tgz";
        sha1 = "4db709fc81bc4a8fd7127a458a5346c5cdce2c6b";
      };
    };
    "lodash.isobject-3.0.2" = {
      name = "lodash.isobject";
      packageName = "lodash.isobject";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isobject/-/lodash.isobject-3.0.2.tgz";
        sha1 = "3c8fb8d5b5bf4bf90ae06e14f2a530a4ed935e1d";
      };
    };
    "machinepack-strings-5.0.0" = {
      name = "machinepack-strings";
      packageName = "machinepack-strings";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/machinepack-strings/-/machinepack-strings-5.0.0.tgz";
        sha1 = "e76a3fd4e0998d7e903195ccec2f09d9e69b258c";
      };
    };
    "machinepack-util-6.0.1" = {
      name = "machinepack-util";
      packageName = "machinepack-util";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/machinepack-util/-/machinepack-util-6.0.1.tgz";
        sha1 = "275b743344db47f4f4400da7e66b4aaca4543212";
      };
    };
    "rttc-9.3.4" = {
      name = "rttc";
      packageName = "rttc";
      version = "9.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/rttc/-/rttc-9.3.4.tgz";
        sha1 = "bc005753b73cd16ac500d91446d6b993206172d7";
      };
    };
    "walker-1.0.7" = {
      name = "walker";
      packageName = "walker";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/walker/-/walker-1.0.7.tgz";
        sha1 = "2f7f9b8fd10d677262b18a884e28d19618e028fb";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "jsonfile-2.4.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-2.4.0.tgz";
        sha1 = "3736a2b428b87bbda0cc83b53fa3d633a35c2ae8";
      };
    };
    "klaw-1.3.1" = {
      name = "klaw";
      packageName = "klaw";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/klaw/-/klaw-1.3.1.tgz";
        sha1 = "4088433b46b3b1ba259d78785d8e96f73ba02439";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "rimraf-2.6.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.2.tgz";
        sha512 = "3kmrqh8xli7rzfm8wc6j9lp0c6vml172iv3z088an9xlwl1xvkvh3fn92za66ms4c9yww80qa5kan31k1z1ypqvkchmh1mznb09xdwn";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha512 = "08vjxzixc9dwc1hn5pd60yyij98krk2pr758aiga97r02ncvaqx1hidi95wk470k1v84gg4alls9bm52m77174z128bgf13b61x951h";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "1879a3j85h92ypvb7lpv1dqpcxl49rqnbgs5la18zmj1yqhwl60c2m74254wbr5pp3znckqpkg9dvjyrz6hfz8b9vag5a3j910db4f8";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.8" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz";
        sha1 = "c07b211c7c952ec1f8efd51a77ef0d1d3990a292";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "hat-0.0.3" = {
      name = "hat";
      packageName = "hat";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hat/-/hat-0.0.3.tgz";
        sha1 = "bb014a9e64b3788aed8005917413d4ff3d502d8a";
      };
    };
    "machine-12.1.1" = {
      name = "machine";
      packageName = "machine";
      version = "12.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/machine/-/machine-12.1.1.tgz";
        sha512 = "397s4d89qj8af92mf10cz5kksmpby18hlysb7rdlxr6dwxzn1rvjpxfqq8z1cylvra6n2z7qb8vmzmd7y96spyjxd5zcdj67kzmz23y";
      };
    };
    "object-hash-0.3.0" = {
      name = "object-hash";
      packageName = "object-hash";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-hash/-/object-hash-0.3.0.tgz";
        sha1 = "548208e43b36a44e4da30bad6c56ac53b885e744";
      };
    };
    "switchback-2.0.0" = {
      name = "switchback";
      packageName = "switchback";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/switchback/-/switchback-2.0.0.tgz";
        sha1 = "2a27d90333def305a7521dcc1e32f6a8e3ad7205";
      };
    };
    "lodash-2.4.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz";
        sha1 = "fadd834b9683073da179b3eae6d9c0d15053f73e";
      };
    };
    "lodash.iserror-3.1.1" = {
      name = "lodash.iserror";
      packageName = "lodash.iserror";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.iserror/-/lodash.iserror-3.1.1.tgz";
        sha1 = "297b9a05fab6714bc2444d7cc19d1d7c44b5ecec";
      };
    };
    "object-hash-0.5.0" = {
      name = "object-hash";
      packageName = "object-hash";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-hash/-/object-hash-0.5.0.tgz";
        sha1 = "e9b784d98b66f416e80de55f2c513710b433fe2d";
      };
    };
    "lodash-3.8.0" = {
      name = "lodash";
      packageName = "lodash";
      version = "3.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-3.8.0.tgz";
        sha1 = "376eb98bdcd9382a9365c33c4cb8250de1325b91";
      };
    };
    "makeerror-1.0.11" = {
      name = "makeerror";
      packageName = "makeerror";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/makeerror/-/makeerror-1.0.11.tgz";
        sha1 = "e01a5c9109f2af79660e4e8b9587790184f5a96c";
      };
    };
    "tmpl-1.0.4" = {
      name = "tmpl";
      packageName = "tmpl";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/tmpl/-/tmpl-1.0.4.tgz";
        sha1 = "23640dd7b42d00433911140820e5cf440e521dd1";
      };
    };
    "request-2.74.0" = {
      name = "request";
      packageName = "request";
      version = "2.74.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.74.0.tgz";
        sha1 = "7693ca768bbb0ea5c8ce08c084a45efa05b892ab";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "bl-1.1.2" = {
      name = "bl";
      packageName = "bl";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.1.2.tgz";
        sha1 = "fdca871a99713aa00d19e3bbba41c44787a65398";
      };
    };
    "caseless-0.11.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.11.0.tgz";
        sha1 = "715b96ea9841593cc33067923f5ec60ebda4f7d7";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-1.0.1" = {
      name = "form-data";
      packageName = "form-data";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-1.0.1.tgz";
        sha1 = "ae315db9a4907fa065502304a66d7733475ee37c";
      };
    };
    "har-validator-2.0.6" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-2.0.6.tgz";
        sha1 = "cdcbc08188265ad119b6a5a7c8ab70eecfb5d27d";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.17" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.17.tgz";
        sha1 = "09d7a393f03e995a79f8af857b70a9e0ab16557a";
      };
    };
    "node-uuid-1.4.8" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.8.tgz";
        sha1 = "b040eb0923968afabf8d32fb1f17f1167fdab907";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "qs-6.2.3" = {
      name = "qs";
      packageName = "qs";
      version = "6.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.2.3.tgz";
        sha1 = "1cfcb25c10a9b2b483053ff39f5dfc9233908cfe";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.3" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.3.tgz";
        sha1 = "0b618a5565b6dea90bf3425d04d55edc475a7561";
      };
    };
    "tunnel-agent-0.4.3" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz";
        sha1 = "6373db76909fe570e08d73583365ed828a74eeeb";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "async-2.6.0" = {
      name = "async";
      packageName = "async";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.0.tgz";
        sha512 = "0zp4b5788400npi1ixjry5x3a4m21c8pnknk8v731rgnwnjbp5ijmfcf5ppmn1ap4a04md1s9dr8n9ygdvrmiai590v0k6dby1wc1y4";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "commander-2.13.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.13.0.tgz";
        sha512 = "1h27ar13gbld2jk6wk84irqmyz6ya6b4dzmxb6nq8azyi48iq8pqqyq90jwzxqb3i7j167y5fpiys6v7vvjzhm8bbd8rya1kzgr4nri";
      };
    };
    "is-my-json-valid-2.17.1" = {
      name = "is-my-json-valid";
      packageName = "is-my-json-valid";
      version = "2.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-my-json-valid/-/is-my-json-valid-2.17.1.tgz";
        sha512 = "2qkjhj6i3y40j35y8k722kklm1j8dfwk9506csa3vxr16vv7125v8jzpmkl551gsif98bzn205yj3sb99xi1i4bd6p5a1m81wvj2sa3";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "generate-function-2.0.0" = {
      name = "generate-function";
      packageName = "generate-function";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-function/-/generate-function-2.0.0.tgz";
        sha1 = "6858fe7c0969b7d4e9093337647ac79f60dfbe74";
      };
    };
    "generate-object-property-1.2.0" = {
      name = "generate-object-property";
      packageName = "generate-object-property";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-object-property/-/generate-object-property-1.2.0.tgz";
        sha1 = "9c0e1c40308ce804f4783618b937fa88f99d50d0";
      };
    };
    "jsonpointer-4.0.1" = {
      name = "jsonpointer";
      packageName = "jsonpointer";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonpointer/-/jsonpointer-4.0.1.tgz";
        sha1 = "4fd92cb34e0e9db3c89c8622ecf51f9b978c6cb9";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "is-property-1.0.2" = {
      name = "is-property";
      packageName = "is-property";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz";
        sha1 = "57fe1c4e48474edd65b09911f26b1cd4095dda84";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "sshpk-1.13.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.13.1.tgz";
        sha1 = "512df6da6287144316dc4c18fe1cf1d940739be3";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "mime-db-1.30.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz";
        sha1 = "74c643da2dd9d6a45399963465b26d5ca7d71f01";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "lodash.isregexp-3.0.5" = {
      name = "lodash.isregexp";
      packageName = "lodash.isregexp";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isregexp/-/lodash.isregexp-3.0.5.tgz";
        sha1 = "e0f596242f2fa228a840086b6c8ad82e4b71fd2d";
      };
    };
    "mailcomposer-2.1.0" = {
      name = "mailcomposer";
      packageName = "mailcomposer";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mailcomposer/-/mailcomposer-2.1.0.tgz";
        sha1 = "a6531822899614fee899c92226d81e2b9cbb183d";
      };
    };
    "mailgun-js-0.7.15" = {
      name = "mailgun-js";
      packageName = "mailgun-js";
      version = "0.7.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/mailgun-js/-/mailgun-js-0.7.15.tgz";
        sha1 = "ee366a20dac64c3c15c03d6c1b3e0ed795252abb";
      };
    };
    "buildmail-2.0.0" = {
      name = "buildmail";
      packageName = "buildmail";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buildmail/-/buildmail-2.0.0.tgz";
        sha1 = "f0b7b0a59e9a4a1b5066bbfa051d248f3832eece";
      };
    };
    "libmime-1.2.0" = {
      name = "libmime";
      packageName = "libmime";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/libmime/-/libmime-1.2.0.tgz";
        sha1 = "8d84b4f3b225b3704410236ef494906436ba742b";
      };
    };
    "addressparser-0.3.2" = {
      name = "addressparser";
      packageName = "addressparser";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/addressparser/-/addressparser-0.3.2.tgz";
        sha1 = "59873f35e8fcf6c7361c10239261d76e15348bb2";
      };
    };
    "libbase64-0.1.0" = {
      name = "libbase64";
      packageName = "libbase64";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/libbase64/-/libbase64-0.1.0.tgz";
        sha1 = "62351a839563ac5ff5bd26f12f60e9830bb751e6";
      };
    };
    "libqp-1.1.0" = {
      name = "libqp";
      packageName = "libqp";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/libqp/-/libqp-1.1.0.tgz";
        sha1 = "f5e6e06ad74b794fb5b5b66988bf728ef1dedbe8";
      };
    };
    "needle-0.10.0" = {
      name = "needle";
      packageName = "needle";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/needle/-/needle-0.10.0.tgz";
        sha1 = "16a24d63f2a61152eb74cce1d12af85c507577d4";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "0q0fsr8bk1m83z0am0h2xn09vyfcf18adscxms8hclznwks1aihsisd96h8npx0idq5wwnypnqrkyk25m5d9zh3dk7rjs29nybc8bkc";
      };
    };
    "iconv-lite-0.4.19" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.19.tgz";
        sha512 = "0jj1pdq3j9ak8cixn2kjp7ip8hf3xgnb85j4jr32yf9rry620v9072c0kk577mllfk1zl9wzs5ypwzbp7vbhf7j31d5rrqgwb0nldm1";
      };
    };
    "async-2.1.5" = {
      name = "async";
      packageName = "async";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.1.5.tgz";
        sha1 = "e587c68580994ac67fc56ff86d3ac56bdbe810bc";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "form-data-2.1.4" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.1.4.tgz";
        sha1 = "33c183acf193276ecaa98143a69e94bfee1750d1";
      };
    };
    "inflection-1.10.0" = {
      name = "inflection";
      packageName = "inflection";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflection/-/inflection-1.10.0.tgz";
        sha1 = "5bffcb1197ad3e81050f8e17e21668087ee9eb2f";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "path-proxy-1.0.0" = {
      name = "path-proxy";
      packageName = "path-proxy";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-proxy/-/path-proxy-1.0.0.tgz";
        sha1 = "18e8a36859fc9d2f1a53b48dee138543c020de5e";
      };
    };
    "proxy-agent-2.0.0" = {
      name = "proxy-agent";
      packageName = "proxy-agent";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-agent/-/proxy-agent-2.0.0.tgz";
        sha1 = "57eb5347aa805d74ec681cb25649dba39c933499";
      };
    };
    "q-1.4.1" = {
      name = "q";
      packageName = "q";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/q/-/q-1.4.1.tgz";
        sha1 = "55705bcd93c5f3673530c2c2cbc0c2b3addc286e";
      };
    };
    "tsscmp-1.0.5" = {
      name = "tsscmp";
      packageName = "tsscmp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tsscmp/-/tsscmp-1.0.5.tgz";
        sha1 = "7dc4a33af71581ab4337da91d85ca5427ebd9a97";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "inflection-1.3.8" = {
      name = "inflection";
      packageName = "inflection";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflection/-/inflection-1.3.8.tgz";
        sha1 = "cbd160da9f75b14c3cc63578d4f396784bf3014e";
      };
    };
    "agent-base-2.1.1" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-2.1.1.tgz";
        sha1 = "d6de10d5af6132d5bd692427d46fc538539094c7";
      };
    };
    "http-proxy-agent-1.0.0" = {
      name = "http-proxy-agent";
      packageName = "http-proxy-agent";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-proxy-agent/-/http-proxy-agent-1.0.0.tgz";
        sha1 = "cc1ce38e453bf984a0f7702d2dd59c73d081284a";
      };
    };
    "https-proxy-agent-1.0.0" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-1.0.0.tgz";
        sha1 = "35f7da6c48ce4ddbfa264891ac593ee5ff8671e6";
      };
    };
    "lru-cache-2.6.5" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "2.6.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-2.6.5.tgz";
        sha1 = "e56d6354148ede8d7707b58d143220fd08df0fd5";
      };
    };
    "pac-proxy-agent-1.1.0" = {
      name = "pac-proxy-agent";
      packageName = "pac-proxy-agent";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pac-proxy-agent/-/pac-proxy-agent-1.1.0.tgz";
        sha512 = "30jd44ckpmfj9prfhzc8bjvn5b5adxk93g9saif813id8mrvl3g1asrhz9l0bc2rp0i779wnhg1rjw80h2y7zk8v02ghq4bdh4hn4a0";
      };
    };
    "socks-proxy-agent-2.1.1" = {
      name = "socks-proxy-agent";
      packageName = "socks-proxy-agent";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks-proxy-agent/-/socks-proxy-agent-2.1.1.tgz";
        sha512 = "33yfj0m61wn7g9s59m7mxhm6w91nkdrd7hcnnbacrj58zqgykpyr7f6lsggvc9xzysrf951ncxh4malqi11yf8z6909fasllxi6cnxh";
      };
    };
    "semver-5.0.3" = {
      name = "semver";
      packageName = "semver";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.0.3.tgz";
        sha1 = "77466de589cd5d3c95f138aa78bc569a3cb5d27a";
      };
    };
    "get-uri-2.0.1" = {
      name = "get-uri";
      packageName = "get-uri";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-uri/-/get-uri-2.0.1.tgz";
        sha512 = "10bm7v59d4pv7pk0smv9qwl8rp1iq60d20jdybycdpjqv85gdirf00kci8m5fz16gja9i5l60yxgiqzafj1195disavn21anrbab9zd";
      };
    };
    "pac-resolver-2.0.0" = {
      name = "pac-resolver";
      packageName = "pac-resolver";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pac-resolver/-/pac-resolver-2.0.0.tgz";
        sha1 = "99b88d2f193fbdeefc1c9a529c1f3260ab5277cd";
      };
    };
    "raw-body-2.3.2" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.3.2.tgz";
        sha1 = "bcd60c77d3eb93cde0050295c3f379389bc88f89";
      };
    };
    "data-uri-to-buffer-1.2.0" = {
      name = "data-uri-to-buffer";
      packageName = "data-uri-to-buffer";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-1.2.0.tgz";
        sha512 = "18vh45y1sdi44vwca9js1hpy9mjwb641dwnc0fm9y2x3pgivzjndjksrlpk65kp5g99lsy2z2m8a4907bj11118c95m2dqg6h6kv95w";
      };
    };
    "ftp-0.3.10" = {
      name = "ftp";
      packageName = "ftp";
      version = "0.3.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/ftp/-/ftp-0.3.10.tgz";
        sha1 = "9197d861ad8142f3e63d5a83bfe4c59f7330885d";
      };
    };
    "file-uri-to-path-1.0.0" = {
      name = "file-uri-to-path";
      packageName = "file-uri-to-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz";
        sha512 = "0px1qliabg53lwfq4izc9vdll68sd08nlczi2ms5nvg7frm3y6zgy07vdvxywazab26jc723qpmh9a6h3bdp685iddzsmgvfarpx6yi";
      };
    };
    "xregexp-2.0.0" = {
      name = "xregexp";
      packageName = "xregexp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xregexp/-/xregexp-2.0.0.tgz";
        sha1 = "52a63e56ca0b84a7f3a5f3d61872f126ad7a5943";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "co-3.0.6" = {
      name = "co";
      packageName = "co";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-3.0.6.tgz";
        sha1 = "1445f226c5eb956138e68c9ac30167ea7d2e6bda";
      };
    };
    "netmask-1.0.6" = {
      name = "netmask";
      packageName = "netmask";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/netmask/-/netmask-1.0.6.tgz";
        sha1 = "20297e89d86f6f6400f250d9f4f6b4c1945fcd35";
      };
    };
    "degenerator-1.0.4" = {
      name = "degenerator";
      packageName = "degenerator";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/degenerator/-/degenerator-1.0.4.tgz";
        sha1 = "fcf490a37ece266464d9cc431ab98c5819ced095";
      };
    };
    "thunkify-2.1.2" = {
      name = "thunkify";
      packageName = "thunkify";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/thunkify/-/thunkify-2.1.2.tgz";
        sha1 = "faa0e9d230c51acc95ca13a361ac05ca7e04553d";
      };
    };
    "ip-1.0.1" = {
      name = "ip";
      packageName = "ip";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip/-/ip-1.0.1.tgz";
        sha1 = "c7e356cdea225ae71b36d70f2e71a92ba4e42590";
      };
    };
    "esprima-3.1.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-3.1.3.tgz";
        sha1 = "fdca51cee6133895e3c88d535ce49dbff62a4633";
      };
    };
    "escodegen-1.9.0" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.9.0.tgz";
        sha512 = "0il8dp1bh3n1am3xx5pazmpjb5m8wzdn9xg1lgh4j8axvsy8v24i1171c04qafx0j4xsaq76j29ljq2srf4i3kdl3qbrn9psjy1hhxz";
      };
    };
    "ast-types-0.10.1" = {
      name = "ast-types";
      packageName = "ast-types";
      version = "0.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ast-types/-/ast-types-0.10.1.tgz";
        sha512 = "2wjsah372x6rjrrsq3bv915lccq4pjpyk4b0vb7kmc87ab5yjgac4rab0qclh6brhhyv95mbyy1k5sijfyx36676darz57k6gsgx3ji";
      };
    };
    "estraverse-4.2.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.2.0.tgz";
        sha1 = "0dee3fed31fcd469618ce7342099fc1afa0bdb13";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "optionator-0.8.2" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz";
        sha1 = "364c5e409d3f4d6301d6c0b4c05bba50180aeb64";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "bytes-3.0.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-3.0.0.tgz";
        sha1 = "d32815404d689699f85a4ea4fa8755dd13a96048";
      };
    };
    "http-errors-1.6.2" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.6.2.tgz";
        sha1 = "0a002cc85707192a7e7946ceedc11155f60ec736";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "depd-1.1.1" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.1.tgz";
        sha1 = "5783b4e1c459f06fa5ca27f991f3d06e7a310359";
      };
    };
    "setprototypeof-1.0.3" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.3.tgz";
        sha1 = "66567e37043eeb4f04d91bd658c0cbefb55b8e04";
      };
    };
    "statuses-1.4.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.4.0.tgz";
        sha512 = "1xxwqpj713rq1idbmp7mj7cj9dl52lazgpd5x8a9g88jawbkn9xpwbgljl7cvnd0jqkll2zpdj5xy63dlis9l2k8vmx1n1gvyv8456f";
      };
    };
    "socks-1.1.10" = {
      name = "socks";
      packageName = "socks";
      version = "1.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks/-/socks-1.1.10.tgz";
        sha1 = "5b8b7fc7c8f341c53ed056e929b7bf4de8ba7b5a";
      };
    };
    "ip-1.1.5" = {
      name = "ip";
      packageName = "ip";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip/-/ip-1.1.5.tgz";
        sha1 = "bdded70114290828c0a039e72ef25f5aaec4354a";
      };
    };
    "smart-buffer-1.1.15" = {
      name = "smart-buffer";
      packageName = "smart-buffer";
      version = "1.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/smart-buffer/-/smart-buffer-1.1.15.tgz";
        sha1 = "7f114b5b65fab3e2a35aa775bb12f0d1c649bf16";
      };
    };
    "rttc-7.4.0" = {
      name = "rttc";
      packageName = "rttc";
      version = "7.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rttc/-/rttc-7.4.0.tgz";
        sha1 = "bc9cacd46add923deb62495a01934eb7ef619fb4";
      };
    };
    "bcryptjs-2.3.0" = {
      name = "bcryptjs";
      packageName = "bcryptjs";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcryptjs/-/bcryptjs-2.3.0.tgz";
        sha1 = "5826900cfef7abaf3425c72e4d464de509b8c2ec";
      };
    };
    "path-parse-1.0.5" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.5.tgz";
        sha1 = "3c1adf871ea9cd6c9431b6ea2bd74a0ff055c4c1";
      };
    };
    "open-0.0.5" = {
      name = "open";
      packageName = "open";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-0.0.5.tgz";
        sha1 = "42c3e18ec95466b6bf0dc42f3a2945c3f0cad8fc";
      };
    };
    "uuid-2.0.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-2.0.2.tgz";
        sha1 = "48bd5698f0677e3c7901a1c46ef15b1643794726";
      };
    };
    "async-2.0.1" = {
      name = "async";
      packageName = "async";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.0.1.tgz";
        sha1 = "b709cc0280a9c36f09f4536be823c838a9049e25";
      };
    };
    "crypto-js-3.1.6" = {
      name = "crypto-js";
      packageName = "crypto-js";
      version = "3.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-js/-/crypto-js-3.1.6.tgz";
        sha1 = "6142651b232dbb8ebdfa9716a70a2888359da6c9";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
  };
in
{
  jStat = nodeEnv.buildNodePackage {
    name = "jStat";
    packageName = "jStat";
    version = "1.7.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/jStat/-/jStat-1.7.1.tgz";
      sha512 = "06i8qrmjarp61v4l425ays18z53kx1cwq67zxifqcdznly3112gxxbijc7sw0dgsjnb8qrbqczzkgrqk6ipnsma6f3irrnldxx9x2xn";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Statistical Library for JavaScript";
      homepage = http://github.com/jstat/jstat;
    };
    production = true;
  };
  stdlib = nodeEnv.buildNodePackage {
    name = "stdlib";
    packageName = "stdlib";
    version = "0.6.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/stdlib/-/stdlib-0.6.0.tgz";
      sha1 = "fe699d0a552e0c37221edba287656a8e426553d5";
    };
    dependencies = [
      sources."machine-13.0.0-24"
      sources."machinepack-arrays-git://github.com/treelinehq/machinepack-arrays.git#fcb0f382ef9b5c546bf1c204bae13dc3bf2b4985"
      sources."machinepack-booleans-git://github.com/treelinehq/machinepack-booleans.git#ae639e06ca108fb930650ffa5b6546f3b8e596de"
      sources."machinepack-console-git://github.com/treelinehq/machinepack-console.git#ec09bcffcb89a446b3d3043b897094c266effeff"
      sources."machinepack-datetime-git://github.com/sgress454/machinepack-datetime.git#7e4cb42fdd17f8e4eb7186579f6116282cc484cd"
      sources."machinepack-dictionaries-git://github.com/treelinehq/machinepack-dictionaries.git#060809c406ace7d276027bc17a9abb6371c7aaa1"
      sources."machinepack-emailaddresses-git://github.com/mikermcneil/machinepack-emailaddresses.git#f88649f4acfe428d31641e2abff718d9c86beeaf"
      (sources."machinepack-fs-git://github.com/mikermcneil/machinepack-fs.git#2a68adb3837c84b3ed80fe87463df2a13649fa95" // {
        dependencies = [
          sources."machinepack-strings-5.0.0"
          sources."machinepack-util-6.0.1"
          sources."machine-12.1.1"
        ];
      })
      sources."machinepack-gravatar-git://github.com/irlnathan/machinepack-gravatar.git#de3e6607c59f354871af3b514808fa290838fb55"
      sources."machinepack-http-3.0.0"
      sources."machinepack-ifthen-git://github.com/treelinehq/machinepack-ifthen.git#2faacb7c60a1d3f3118df7e585c1e228bc5a5940"
      sources."machinepack-json-git://github.com/treelinehq/machinepack-json.git#cb9b172d24d8a5f6a12f3ad63d95d6985fb2bd70"
      sources."machinepack-mailgun-git://github.com/particlebanana/machinepack-mailgun.git#d473ed00e7195297226740b01a87b01e4149a545"
      sources."machinepack-math-git://github.com/treelinehq/machinepack-math.git#e33233cc2129098b297eafc14c17dcf88f714244"
      sources."machinepack-numbers-git://github.com/treelinehq/machinepack-numbers.git#cdbbccef1fa7e6cbc9549b2b70415c7316ebaa79"
      sources."machinepack-passwords-git://github.com/mikermcneil/machinepack-passwords.git#a79274800db769840996498f170258c74118bc2d"
      sources."machinepack-paths-git://github.com/treelinehq/machinepack-paths.git#2d25ec774bbca6e3de00ff4f3b975e6f421f6da4"
      sources."machinepack-process-git://github.com/treelinehq/machinepack-process.git#4c9fe46cb0f666e88bd5f0e31ffaf5eaaff1639f"
      sources."machinepack-strings-git://github.com/treelinehq/machinepack-strings.git#6f429144064c573da4d92226b22d4a7a14d22e94"
      sources."machinepack-urls-git://github.com/mikermcneil/machinepack-urls.git#49388b3bdba5c9a780834c2c5d29d388a1cf4d90"
      sources."machinepack-util-git://github.com/treelinehq/machinepack-util.git#d9866079e883e7db185f91284cfab890f3f430f4"
      sources."@sailshq/lodash-3.10.2"
      sources."convert-to-ecmascript-compatible-varname-0.1.4"
      sources."debug-2.2.0"
      sources."include-all-1.0.8"
      sources."rttc-9.8.2"
      sources."switchback-2.0.0"
      sources."ms-0.7.1"
      sources."lodash-3.10.1"
      sources."async-2.0.1"
      sources."moment-2.15.2"
      sources."moment-timezone-0.3.1"
      sources."browserify-transform-machinepack-1.0.3"
      sources."browserify-transform-tools-1.7.0"
      sources."falafel-2.1.0"
      sources."through-2.3.8"
      sources."acorn-5.3.0"
      sources."foreach-2.0.5"
      sources."isarray-0.0.1"
      sources."object-keys-1.0.11"
      sources."validator-3.43.0"
      sources."fs-extra-0.30.0"
      sources."lodash.isfunction-3.0.8"
      sources."lodash.isobject-3.0.2"
      sources."walker-1.0.7"
      sources."graceful-fs-4.1.11"
      sources."jsonfile-2.4.0"
      sources."klaw-1.3.1"
      sources."path-is-absolute-1.0.1"
      sources."rimraf-2.6.2"
      sources."glob-7.1.2"
      sources."fs.realpath-1.0.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."minimatch-3.0.4"
      sources."once-1.4.0"
      sources."wrappy-1.0.2"
      sources."brace-expansion-1.1.8"
      sources."balanced-match-1.0.0"
      sources."concat-map-0.0.1"
      sources."hat-0.0.3"
      sources."object-hash-0.5.0"
      sources."lodash.iserror-3.1.1"
      sources."makeerror-1.0.11"
      sources."tmpl-1.0.4"
      sources."request-2.74.0"
      sources."aws-sign2-0.6.0"
      sources."aws4-1.6.0"
      sources."bl-1.1.2"
      sources."caseless-0.11.0"
      sources."combined-stream-1.0.5"
      sources."extend-3.0.1"
      sources."forever-agent-0.6.1"
      sources."form-data-2.1.4"
      sources."har-validator-2.0.6"
      sources."hawk-3.1.3"
      sources."http-signature-1.1.1"
      sources."is-typedarray-1.0.0"
      sources."isstream-0.1.2"
      sources."json-stringify-safe-5.0.1"
      sources."mime-types-2.1.17"
      sources."node-uuid-1.4.8"
      sources."oauth-sign-0.8.2"
      sources."qs-6.2.3"
      sources."stringstream-0.0.5"
      sources."tough-cookie-2.3.3"
      sources."tunnel-agent-0.4.3"
      sources."readable-stream-1.1.14"
      sources."core-util-is-1.0.2"
      sources."process-nextick-args-1.0.7"
      sources."string_decoder-0.10.31"
      sources."util-deprecate-1.0.2"
      sources."delayed-stream-1.0.0"
      sources."chalk-1.1.3"
      sources."commander-2.13.0"
      sources."is-my-json-valid-2.17.1"
      sources."pinkie-promise-2.0.1"
      sources."ansi-styles-2.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."ansi-regex-2.1.1"
      sources."generate-function-2.0.0"
      sources."generate-object-property-1.2.0"
      sources."jsonpointer-4.0.1"
      sources."xtend-4.0.1"
      sources."is-property-1.0.2"
      sources."pinkie-2.0.4"
      sources."hoek-2.16.3"
      sources."boom-2.10.1"
      sources."cryptiles-2.0.5"
      sources."sntp-1.0.9"
      sources."assert-plus-1.0.0"
      sources."jsprim-1.4.1"
      sources."sshpk-1.13.1"
      sources."extsprintf-1.3.0"
      sources."json-schema-0.2.3"
      sources."verror-1.10.0"
      sources."asn1-0.2.3"
      sources."dashdash-1.14.1"
      sources."getpass-0.1.7"
      sources."jsbn-0.1.1"
      sources."tweetnacl-0.14.5"
      sources."ecc-jsbn-0.1.1"
      sources."bcrypt-pbkdf-1.0.1"
      sources."mime-db-1.30.0"
      sources."punycode-1.4.1"
      sources."lodash.isregexp-3.0.5"
      sources."mailcomposer-2.1.0"
      sources."mailgun-js-0.7.15"
      sources."buildmail-2.0.0"
      sources."libmime-1.2.0"
      sources."addressparser-0.3.2"
      sources."libbase64-0.1.0"
      sources."libqp-1.1.0"
      sources."needle-0.10.0"
      sources."iconv-lite-0.4.19"
      sources."inflection-1.3.8"
      sources."is-stream-1.1.0"
      sources."path-proxy-1.0.0"
      sources."proxy-agent-2.0.0"
      sources."q-1.4.1"
      sources."tsscmp-1.0.5"
      sources."asynckit-0.4.0"
      sources."agent-base-2.1.1"
      sources."http-proxy-agent-1.0.0"
      sources."https-proxy-agent-1.0.0"
      sources."lru-cache-2.6.5"
      sources."pac-proxy-agent-1.1.0"
      sources."socks-proxy-agent-2.1.1"
      sources."semver-5.0.3"
      sources."get-uri-2.0.1"
      sources."pac-resolver-2.0.0"
      sources."raw-body-2.3.2"
      sources."data-uri-to-buffer-1.2.0"
      sources."ftp-0.3.10"
      sources."file-uri-to-path-1.0.0"
      sources."xregexp-2.0.0"
      sources."co-3.0.6"
      sources."netmask-1.0.6"
      sources."degenerator-1.0.4"
      sources."thunkify-2.1.2"
      sources."ip-1.1.5"
      sources."esprima-3.1.3"
      sources."escodegen-1.9.0"
      sources."ast-types-0.10.1"
      sources."estraverse-4.2.0"
      sources."esutils-2.0.2"
      sources."optionator-0.8.2"
      sources."source-map-0.5.7"
      sources."prelude-ls-1.1.2"
      sources."deep-is-0.1.3"
      sources."wordwrap-1.0.0"
      sources."type-check-0.3.2"
      sources."levn-0.3.0"
      sources."fast-levenshtein-2.0.6"
      sources."bytes-3.0.0"
      sources."http-errors-1.6.2"
      sources."unpipe-1.0.0"
      sources."depd-1.1.1"
      sources."setprototypeof-1.0.3"
      sources."statuses-1.4.0"
      sources."socks-1.1.10"
      sources."smart-buffer-1.1.15"
      sources."bcryptjs-2.3.0"
      sources."path-parse-1.0.5"
      sources."open-0.0.5"
      sources."uuid-2.0.2"
      sources."crypto-js-3.1.6"
      sources."resolve-1.1.7"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The framework-agnostic subset of sails-stdlib.  Hand-picked and maintained by the Sails.js core team.";
      license = "MIT";
    };
    production = true;
  };
}