{ pythonPackages
}:

[
(pythonPackages.simplejson)
(pythonPackages.six)
(pythonPackages.botocore)
(pythonPackages.python-dateutil)
(pythonPackages.setuptools)
(pythonPackages.pip)
(pythonPackages.pyyaml)
(pythonPackages.pyasn1)
(pythonPackages.s3transfer)
(pythonPackages.docutils)
(pythonPackages.requests)
(pythonPackages.futures)
(pythonPackages.jmespath)
(pythonPackages.awscli)
(pythonPackages.wheel)
(pythonPackages.rsa)
(pythonPackages.colorama)
(pythonPackages.idna)
(pythonPackages.certifi)
(pythonPackages.urllib3)
# (pythonPackages.awscli-cwlogs)
(pythonPackages.chardet)
(pythonPackages.cffi)
(pythonPackages.pbr)
(pythonPackages.virtualenv)
(pythonPackages.pytz)
(pythonPackages.pycparser)
(pythonPackages.jinja2)
(pythonPackages.boto3)
(pythonPackages.setuptools_scm)
(pythonPackages.markupsafe)
(pythonPackages.enum34)
(pythonPackages.cryptography)
(pythonPackages.boto)
(pythonPackages.asn1crypto)
(pythonPackages.ipaddress)
(pythonPackages.pytestrunner)
(pythonPackages.lxml)
(pythonPackages.numpy)
(pythonPackages.pyopenssl)
(pythonPackages.pyparsing)
## (pythonPackages.flask)
(pythonPackages.decorator)
(pythonPackages.psutil)
(pythonPackages.click)
(pythonPackages.werkzeug)
(pythonPackages.sqlalchemy)
(pythonPackages.argparse)
(pythonPackages.mock)
(pythonPackages.future)
(pythonPackages.pandas)
(pythonPackages.tornado)
(pythonPackages.pyasn1-modules)
(pythonPackages.funcsigs)
(pythonPackages.nose)
(pythonPackages.psycopg2)
(pythonPackages.coverage)
(pythonPackages.httplib2)
(pythonPackages.jsonschema)
(pythonPackages.protobuf)
(pythonPackages.pygments)
(pythonPackages.vcversioner)
(pythonPackages.pytest)
(pythonPackages.singledispatch)
(pythonPackages.paramiko)
(pythonPackages.oauth2client)
(pythonPackages.py)
(pythonPackages.itsdangerous)
(pythonPackages.functools32)
(pythonPackages.mccabe)
(pythonPackages.pillow)
(pythonPackages.ptyprocess)
(pythonPackages.pexpect)
# (pythonPackages.babel)
(pythonPackages.backports_abc)
(pythonPackages.docopt)
(pythonPackages.selenium)
(pythonPackages.redis)
(pythonPackages.zope_interface)
# (pythonPackages.grpcio)
(pythonPackages.pyflakes)
# (pythonPackages.django)
(pythonPackages.wrapt)
(pythonPackages.bcrypt)
(pythonPackages.flake8)
(pythonPackages.markdown)
(pythonPackages.pynacl)
(pythonPackages.websocket_client)
(pythonPackages.pycodestyle)
(pythonPackages.html5lib)
(pythonPackages.elasticsearch)
(pythonPackages.ipython)
(pythonPackages.pycrypto)
(pythonPackages.scipy)
(pythonPackages.backports_ssl_match_hostname)
(pythonPackages.configparser)
(pythonPackages.arrow)
(pythonPackages.matplotlib)
(pythonPackages.gevent)
(pythonPackages.scikitlearn)
(pythonPackages.wcwidth)
(pythonPackages.beautifulsoup4)
(pythonPackages.greenlet)
(pythonPackages.amqp)
(pythonPackages.unittest2)
(pythonPackages.ordereddict)
(pythonPackages.uritemplate)
(pythonPackages.gunicorn)
(pythonPackages.packaging)
# (pythonPackages.google-api-python-client)
(pythonPackages.traitlets)
(pythonPackages.prompt_toolkit)
(pythonPackages.ipython_genutils)
# (pythonPackages.googleapis-common-protos)
(pythonPackages.kombu)
(pythonPackages.linecache2)
(pythonPackages.traceback2)
(pythonPackages.typing)
(pythonPackages.pymysql)
(pythonPackages.bleach)
# (pythonPackages.google-auth)
(pythonPackages.stevedore)
(pythonPackages.pickleshare)
(pythonPackages.appdirs)
(pythonPackages.simplegeneric)
(pythonPackages.cython)
# (pythonPackages.google-gax)
(pythonPackages.lockfile)
# (pythonPackages.google-cloud-core)
(pythonPackages.cycler)
(pythonPackages.msgpack)
(pythonPackages.oauthlib)
(pythonPackages.requests_oauthlib)
(pythonPackages.pymongo)
(pythonPackages.pylint)
(pythonPackages.GitPython)
(pythonPackages.sphinx)
(pythonPackages.celery)
(pythonPackages.billiard)
(pythonPackages.olefile)
(pythonPackages.astroid)
(pythonPackages.xmltodict)
(pythonPackages.isort)
(pythonPackages.snowballstemmer)
(pythonPackages.pep8)
(pythonPackages.monotonic)
# (pythonPackages.ccxt)
(pythonPackages.ply)
(pythonPackages.netaddr)
(pythonPackages.alabaster)
## (pythonPackages.flask-restful)
(pythonPackages.docker_pycreds)
(pythonPackages.lazy-object-proxy)
(pythonPackages.attrs)
(pythonPackages.pyjwt)
# (pythonPackages.google-cloud-logging)
(pythonPackages.imagesize)
(pythonPackages.ujson)
(pythonPackages.ndg-httpsclient)
(pythonPackages.configobj)
(pythonPackages.raven)
# (pythonPackages.gitdb2)
(pythonPackages.tabulate)
(pythonPackages.unidecode)
(pythonPackages.netifaces)
# (pythonPackages.gapic-google-cloud-logging-v2)
(pythonPackages.sqlparse)
# (pythonPackages.smmap2)
(pythonPackages.incremental)
(pythonPackages.Mako)
(pythonPackages.pyzmq)
(pythonPackages.pytestcov)
# (pythonPackages.ansible)
(pythonPackages.contextlib2)
(pythonPackages.cachetools)
(pythonPackages.tqdm)
(pythonPackages.flask_sqlalchemy)
(pythonPackages.iso8601)
# (pythonPackages.configargparse)
(pythonPackages.subprocess32)
(pythonPackages.parsedatetime)
(pythonPackages.tzlocal)
(pythonPackages.requests-toolbelt)
(pythonPackages.retrying)
(pythonPackages.vine)
(pythonPackages.supervisor)
(pythonPackages.nbformat)
(pythonPackages.prettytable)
(pythonPackages.xlrd)
(pythonPackages.tox)
(pythonPackages.pythondaemon)
(pythonPackages.backports_functools_lru_cache)
(pythonPackages.jupyter_core)
# (pythonPackages.djangorestframework)
(pythonPackages.webencodings)
# (pythonPackages.docker-py)
(pythonPackages.pluggy)
# (pythonPackages.grpc-google-cloud-logging-v2)
(pythonPackages.jedi)
(pythonPackages.cached-property)
(pythonPackages.unicodecsv)
# (pythonPackages.uwsgi)
(pythonPackages.sphinxcontrib-websupport)
(pythonPackages.thrift)
# (pythonPackages.oslo-i18n)
(pythonPackages.blessings)
# (pythonPackages.mysql-python)
(pythonPackages.statsd)
(pythonPackages.debtcollector)
(pythonPackages.ecdsa)
# (pythonPackages.oslo-utils)
# (pythonPackages.oslo-config)
# (pythonPackages.oslo-serialization)
(pythonPackages.networkx)
(pythonPackages.zope_component)
(pythonPackages.pathlib2)
(pythonPackages.meld3)
(pythonPackages.scandir)
(pythonPackages.pyRFC3339)
(pythonPackages.zope_event)
# (pythonPackages.tensorflow-tensorboard)
(pythonPackages.openpyxl)
(pythonPackages.alembic)
(pythonPackages.rfc3986)
(pythonPackages.augeas)
(pythonPackages.docker)
(pythonPackages.acme)
(pythonPackages.mistune)
# (pythonPackages.keystoneauth1)
(pythonPackages.isodate)
# (pythonPackages.certbot)
(pythonPackages.regex)
(pythonPackages.texttable)
(pythonPackages.service-identity)
# (pythonPackages.certbot-apache)
# (pythonPackages.tensorflow)
# (pythonPackages.mozsystemmonitor)
(pythonPackages.Fabric)
# (pythonPackages.letsencrypt)
# (pythonPackages.blobuploader)
(pythonPackages.backports_shutil_get_terminal_size)
(pythonPackages.datadog)
(pythonPackages.dockerpty)
(pythonPackages.python_magic)
(pythonPackages.jdcal)
# (pythonPackages.requests-file)
(pythonPackages.dill)
(pythonPackages.python-editor)
(pythonPackages.twisted)
(pythonPackages.anyjson)
(pythonPackages.pystache)
# (pythonPackages.tldextract)
# (pythonPackages.parso)
(pythonPackages.keystoneclient)
(pythonPackages.ipykernel)
(pythonPackages.freezegun)
(pythonPackages.nbconvert)
(pythonPackages.et_xmlfile)
# (pythonPackages.frida)
(pythonPackages.webob)
# (pythonPackages.mmh3)
# (pythonPackages.apache-beam)
(pythonPackages.termcolor)
(pythonPackages.jupyter_client)
# (pythonPackages.certbot-nginx)
(pythonPackages.notebook)
(pythonPackages.w3lib)
# (pythonPackages.grpcio-tools)
(pythonPackages.backports_weakref)
(pythonPackages.dns)
(pythonPackages.ipywidgets)
(pythonPackages.gflags)
# (pythonPackages.ruamel_yaml)
# (pythonPackages.cliff)
(pythonPackages.entrypoints)
# (pythonPackages.easyprocess)
(pythonPackages.python_mimeparse)
(pythonPackages.kazoo)
(pythonPackages.defusedxml)
(pythonPackages.widgetsnbextension)
(pythonPackages.cmd2)
(pythonPackages.testpath)
(pythonPackages.pandocfilters)
(pythonPackages.h5py)
(pythonPackages.pika)
(pythonPackages.passlib)
(pythonPackages.qtconsole)
# (pythonPackages.opencv-python)
(pythonPackages.swiftclient)
# (pythonPackages.altgraph)
# (pythonPackages.sklearn)
# (pythonPackages.macholib)
(pythonPackages.docker_compose)
(pythonPackages.memcached)
(pythonPackages.nltk)
(pythonPackages.novaclient)
# (pythonPackages.positional)
(pythonPackages.sympy)
(pythonPackages.cssselect)
(pythonPackages.plotly)
# (pythonPackages.ua-parser)
(pythonPackages.pytest_xdist)
(pythonPackages.azure-storage)
(pythonPackages.argh)
(pythonPackages.faker)
(pythonPackages.jupyter)
# (pythonPackages.django-extensions)
(pythonPackages.jupyter_console)
# (pythonPackages.multidict)
(pythonPackages.execnet)
(pythonPackages.jsonpatch)
(pythonPackages.pyaml)
# (pythonPackages.os-client-config)
(pythonPackages.python-slugify)
(pythonPackages.joblib)
(pythonPackages.terminado)
(pythonPackages.requestsexceptions)
# (pythonPackages.google-cloud-storage)
# (pythonPackages.pytesseract)
(pythonPackages.pathlib)
(pythonPackages.patsy)
# (pythonPackages.hjson)
(pythonPackages.blinker)
(pythonPackages.apipkg)
(pythonPackages.capstone)
# (pythonPackages.newrelic)
(pythonPackages.codecov)
(pythonPackages.bz2file)
# (pythonPackages.fake-useragent)
# (pythonPackages.mysqlclient)
(pythonPackages.Keras)
# (pythonPackages.sphinx-rtd-theme)
# (pythonPackages.distribute)
(pythonPackages.dask)
(pythonPackages.geopy)
# (pythonPackages.pyhocon)
(pythonPackages.smart_open)
(pythonPackages.azure-common)
(pythonPackages.jsonpointer)
# (pythonPackages.django-filter)
(pythonPackages.seaborn)
(pythonPackages.mxnet)
(pythonPackages.statsmodels)
# (pythonPackages.scrapy-crawlera)
(pythonPackages.python-jenkins)
(pythonPackages.inflection)
(pythonPackages.whichcraft)
(pythonPackages.constantly)
(pythonPackages.binaryornot)
(pythonPackages.cookiecutter)
# (pythonPackages.aiohttp)
(pythonPackages.jinja2_time)
(pythonPackages.sqlalchemy_migrate)
# (pythonPackages.py4j)
(pythonPackages.poyo)
(pythonPackages.wtforms)
(pythonPackages.pathspec)
# (pythonPackages.xlsxwriter)
# (pythonPackages.gcloud)
(pythonPackages.pyperclip)
(pythonPackages.repoze_lru)
# (pythonPackages.google-resumable-media)
(pythonPackages.automat)
(pythonPackages.flask_wtf)
(pythonPackages.tenacity)
(pythonPackages.fuzzywuzzy)
(pythonPackages.python-jose)
(pythonPackages.waitress)
# (pythonPackages.django-debug-toolbar)
(pythonPackages.python-glanceclient)
(pythonPackages.hyperlink)
# (pythonPackages.async-timeout)
(pythonPackages.shapely)
(pythonPackages.aniso8601)
(pythonPackages.python-cinderclient)
(pythonPackages.multi-key-dict)
(pythonPackages.coveralls)
(pythonPackages.python-openstackclient)
(pythonPackages.setuptools-git)
(pythonPackages.azure-nspkg)
(pythonPackages.pyodbc)
(pythonPackages.openstacksdk)
(pythonPackages.eventlet)
(pythonPackages.bokeh)
(pythonPackages.maxminddb)
(pythonPackages.google-cloud-bigquery)
## (pythonPackages.flask-login)
(pythonPackages.cookies)
(pythonPackages.s3cmd)
## (pythonPackages.flask-script)
# (pythonPackages.django-cors-headers)
# (pythonPackages.yarl)
(pythonPackages.argcomplete)
(pythonPackages.testtools)
(pythonPackages.warlock)
(pythonPackages.cassandra-driver)
(pythonPackages.pyserial)
(pythonPackages.watchdog)
(pythonPackages.paste)
(pythonPackages.pytestmock)
(pythonPackages.fasteners)
(pythonPackages.pathtools)
(pythonPackages.enum-compat)
(pythonPackages.factory-boy)
(pythonPackages.crcmod)
(pythonPackages.suds-jurko)
(pythonPackages.pysftp)
(pythonPackages.sqlobject)
(pythonPackages.pysocks)
(pythonPackages.keyring)
(pythonPackages.grpc-google-pubsub-v1)
(pythonPackages.grpc-google-logging-v2)
(pythonPackages.extras)
(pythonPackages.semantic-version)
(pythonPackages.kafka-python)
(pythonPackages.user-agents)
(pythonPackages.pastedeploy)
(pythonPackages.python-subunit)
(pythonPackages.azure)
(pythonPackages.python-jwt)
# (pythonPackages.suds)
(pythonPackages.tempita)
(pythonPackages.geoip2)
(pythonPackages.filechunkio)
(pythonPackages.webtest)
(pythonPackages.numexpr)
(pythonPackages.gax-google-pubsub-v1)
(pythonPackages.gitdb)
(pythonPackages.smmap)
(pythonPackages.slackclient)
(pythonPackages.gax-google-logging-v2)
(pythonPackages.fixtures)
(pythonPackages.httpretty)
(pythonPackages.sh)
(pythonPackages.moto)
(pythonPackages.slacker)
(pythonPackages.xlwt)
(pythonPackages.jws)
## (pythonPackages.flask-cors)
(pythonPackages.pydevd)
(pythonPackages.pycurl)
(pythonPackages.google-cloud-pubsub)
(pythonPackages.hgtools)
(pythonPackages.pager)
(pythonPackages.google-auth-httplib2)
(pythonPackages.setproctitle)
# (pythonPackages.django-storages)
(pythonPackages.google-cloud-datastore)
(pythonPackages.ipaddr)
(pythonPackages.glob2)
# (pythonPackages.django-appconf)
(pythonPackages.autopep8)
(pythonPackages.ptvsd)
(pythonPackages.ipdb)
(pythonPackages.youtube-dl)
(pythonPackages.hiredis)
# (pythonPackages.importlib)
(pythonPackages.bottle)
(pythonPackages.azure-mgmt-compute)
(pythonPackages.taskcluster)
(pythonPackages.slugid)
(pythonPackages.toolz)
(pythonPackages.validate-email)
(pythonPackages.mpmath)
(pythonPackages.pyhawk-with-a-single-extra-commit)
(pythonPackages.cookiejar)
(pythonPackages.bs4)
(pythonPackages.pkginfo)
(pythonPackages.voluptuous)
(pythonPackages.mxnet-mkl)
(pythonPackages.jsonpickle)
(pythonPackages.marshmallow)
(pythonPackages.applicationinsights)
# (pythonPackages.dateparser)
(pythonPackages.colorlog)
(pythonPackages.httpagentparser)
(pythonPackages.osc-lib)
(pythonPackages.parse)
(pythonPackages.twilio)
(pythonPackages.dicttoxml)
(pythonPackages.subliminal)
(pythonPackages.requests-mock)
(pythonPackages.reportlab)
(pythonPackages.pytestdjango)
(pythonPackages.stripe)
(pythonPackages.google-cloud-vision)
(pythonPackages.coala)
(pythonPackages.google-cloud-language)
(pythonPackages.tmdbsimple)
(pythonPackages.google-cloud-speech)
(pythonPackages.google-cloud-bigtable)
(pythonPackages.azure-mgmt-resource)
(pythonPackages.theano)
(pythonPackages.google-cloud-translate)
(pythonPackages.google-cloud-error-reporting)
(pythonPackages.google-cloud-monitoring)
(pythonPackages.ddt)
(pythonPackages.azure-mgmt-network)
(pythonPackages.google-cloud-runtimeconfig)
(pythonPackages.gensim)
(pythonPackages.path-py)
(pythonPackages.google-cloud-dns)
(pythonPackages.google-cloud-resource-manager)
(pythonPackages.gapic-google-cloud-datastore-v1)
(pythonPackages.beautifulsoup)
(pythonPackages.pytestforked)
## (pythonPackages.flask-migrate)
(pythonPackages.zc-buildout)
(pythonPackages.google-cloud-spanner)
(pythonPackages.flexget)
(pythonPackages.pyinotify)
(pythonPackages.azure-mgmt-storage)
# (pythonPackages.oslo-context)
(pythonPackages.elasticsearch-dsl)
(pythonPackages.python-heatclient)
(pythonPackages.aws-requests-auth)
(pythonPackages.azure-mgmt-nspkg)
(pythonPackages.virtualenv-clone)
# (pythonPackages.oslo-log)
(pythonPackages.hypothesis)
(pythonPackages.python-geohash)
(pythonPackages.cx-oracle)
(pythonPackages.unittest-xml-reporting)
(pythonPackages.feedparser)
(pythonPackages.pytesttimeout)
(pythonPackages.flower)
(pythonPackages.pytimeparse)
(pythonPackages.dj-database-url)
(pythonPackages.grpc-google-iam-v1)
# (pythonPackages.oslo-concurrency)
(pythonPackages.croniter)
(pythonPackages.pytesthtml)
(pythonPackages.twine)
(pythonPackages.gspread)
(pythonPackages.humanize)
(pythonPackages.bcdoc)
(pythonPackages.hacking)
(pythonPackages.pycryptodome)
(pythonPackages.sortedcontainers)
(pythonPackages.proto-google-cloud-logging-v2)
(pythonPackages.google-cloud-videointelligence)
(pythonPackages.pycountry)
(pythonPackages.dogpile-cache)
(pythonPackages.carbon)
(pythonPackages.python-ldap)
(pythonPackages.haversine)
(pythonPackages.responses)
(pythonPackages.ruamel-ordereddict)
(pythonPackages.humanfriendly)
(pythonPackages.parse-type)
(pythonPackages.whitenoise)
# (pythonPackages.django-nose)
(pythonPackages.troposphere)
(pythonPackages.deprecation)
(pythonPackages.google-cloud)
(pythonPackages.adal)
(pythonPackages.apscheduler)
(pythonPackages.graphite-web)
(pythonPackages.pyzabbix)
(pythonPackages.python-levenshtein)
(pythonPackages.influxdb)
(pythonPackages.secretstorage)
(pythonPackages.qds-sdk)
(pythonPackages.cement)
(pythonPackages.python-ironicclient)
(pythonPackages.azure-servicebus)
(pythonPackages.cov-core)
(pythonPackages.msrest)
(pythonPackages.phonenumbers)
(pythonPackages.tweepy)
(pythonPackages.pypdf2)
(pythonPackages.pipenv)
(pythonPackages.invoke)
(pythonPackages.plumbum)
(pythonPackages.msrestazure)
(pythonPackages.graphviz)
(pythonPackages.azure-servicemanagement-legacy)
(pythonPackages.sasl)
(pythonPackages.azure-mgmt)
(pythonPackages.sqlalchemy-utils)
(pythonPackages.gapic-google-cloud-error-reporting-v1beta1)
# (pythonPackages.django-redis)
(pythonPackages.awsebcli)
(pythonPackages.proto-google-cloud-error-reporting-v1beta1)
(pythonPackages.python-openid)
(pythonPackages.gapic-google-cloud-spanner-v1)
(pythonPackages.blessed)
(pythonPackages.gapic-google-cloud-spanner-admin-database-v1)
(pythonPackages.gapic-google-cloud-spanner-admin-instance-v1)
(pythonPackages.proto-google-cloud-spanner-v1)
(pythonPackages.proto-google-cloud-spanner-admin-database-v1)
(pythonPackages.requests-ntlm)
(pythonPackages.proto-google-cloud-spanner-admin-instance-v1)
(pythonPackages.virtualenvwrapper)
(pythonPackages.gapic-google-cloud-pubsub-v1)
(pythonPackages.munch)
(pythonPackages.avro)
(pythonPackages.dbfread)
(pythonPackages.python-twitter)
(pythonPackages.falcon)
(pythonPackages.zope_deprecation)
(pythonPackages.csvkit)
# (pythonPackages.django-compressor)
(pythonPackages.flake8-import-order)
(pythonPackages.pywavelets)
(pythonPackages.pydns)
# (pythonPackages.django-model-utils)
(pythonPackages.python-neutronclient)
(pythonPackages.pydispatcher)
# (pythonPackages.django-rest-swagger)
(pythonPackages.mrjob)
(pythonPackages.proto-google-cloud-pubsub-v1)
(pythonPackages.agate)
(pythonPackages.paho-mqtt)
(pythonPackages.proto-google-cloud-datastore-v1)
(pythonPackages.scrapy)
(pythonPackages.pywinrm)
(pythonPackages.more-itertools)
(pythonPackages.coreapi)
(pythonPackages.agate-excel)
(pythonPackages.agate-dbf)
(pythonPackages.jsonpath-rw)
(pythonPackages.jsonfield)
(pythonPackages.queuelib)
(pythonPackages.ggplot)
(pythonPackages.requests-futures)
# (pythonPackages.django-celery)
(pythonPackages.brewer2mpl)
# (pythonPackages.tensorflow-gpu)
(pythonPackages.pip-tools)
(pythonPackages.testfixtures)
(pythonPackages.python-dotenv)
(pythonPackages.scikit-image)
(pythonPackages.brotlipy)
(pythonPackages.peewee)
(pythonPackages.pyxdg)
(pythonPackages.pymssql)
(pythonPackages.cssutils)
## (pythonPackages.flask-cache)
# (pythonPackages.appnope)
(pythonPackages.logilab-common)
(pythonPackages.agate-sql)
(pythonPackages.cachet)
(pythonPackages.scp)
(pythonPackages.jira)
(pythonPackages.parsel)
(pythonPackages.python-json-logger)
(pythonPackages.testrepository)
(pythonPackages.enum)
(pythonPackages.pypiwin32)
(pythonPackages.leather)
(pythonPackages.send2trash)
(pythonPackages.ntlm-auth)
(pythonPackages.pyvirtualdisplay)
(pythonPackages.pyhive)
(pythonPackages.pyhamcrest)
(pythonPackages.retry)
(pythonPackages.cherrypy)
(pythonPackages.bitarray)
(pythonPackages.yarg)
(pythonPackages.itypes)
(pythonPackages.jpype1)
(pythonPackages.dulwich)
(pythonPackages.empy)
(pythonPackages.python-keyczar)
# (pythonPackages.os-testr)
(pythonPackages.python-consul)
(pythonPackages.routes)
(pythonPackages.first)
(pythonPackages.xgboost)
(pythonPackages.pydocstyle)
(pythonPackages.junit-xml)
(pythonPackages.rtorrent-python)
(pythonPackages.python-fanart)
(pythonPackages.tables)
(pythonPackages.google-apputils)
(pythonPackages.pykube)
(pythonPackages.robotframework)
(pythonPackages.behave)
(pythonPackages.gcdt-bundler)
(pythonPackages.coreschema)
(pythonPackages.testscenarios)
(pythonPackages.wand)
(pythonPackages.nosexcover)
# (pythonPackages.django-crispy-forms)
(pythonPackages.fake-factory)
(pythonPackages.pymc)
(pythonPackages.coala-bears)
(pythonPackages.httpbin)
(pythonPackages.prettyplotlib)
# (pythonPackages.oslo-messaging)
# (pythonPackages.django-braces)
(pythonPackages.libtmux)
(pythonPackages.iptools)
(pythonPackages.appier)
(pythonPackages.pyproj)
(pythonPackages.whoosh)
(pythonPackages.google-compute-engine)
(pythonPackages.googleads)
# (pythonPackages.websockets)
(pythonPackages.clint)
(pythonPackages.inflect)
# (pythonPackages.pybrain)
(pythonPackages.findspark)
(pythonPackages.ldap3)
# (pythonPackages.oslo-db)
(pythonPackages.docker-buildtool)
# (pythonPackages.oslo-middleware)
(pythonPackages.requests-aws4auth)
(pythonPackages.retry-decorator)
(pythonPackages.azure-mgmt-monitor)
(pythonPackages.python-gnupg)
(pythonPackages.thriftpy)
(pythonPackages.args)
(pythonPackages.azure-mgmt-trafficmanager)
(pythonPackages.prometheus-client)
(pythonPackages.gcs-oauth2-boto-plugin)
# (pythonPackages.futurist)
(pythonPackages.sat)
(pythonPackages.azure-mgmt-batch)
(pythonPackages.azure-batch)
(pythonPackages.email-validator)
(pythonPackages.trueskill)
(pythonPackages.autobahn)
(pythonPackages.azure-mgmt-redis)
(pythonPackages.oauth2)
## (pythonPackages.flask-basicauth)
(pythonPackages.azure-mgmt-keyvault)
(pythonPackages.pythonwhois)
(pythonPackages.socksipy-branch)
(pythonPackages.mox3)
(pythonPackages.gdata)
(pythonPackages.zeep)
(pythonPackages.commonmark)
(pythonPackages.nodeenv)
# (pythonPackages.rpy2)
(pythonPackages.thrift-sasl)
(pythonPackages.openstackdocstheme)
(pythonPackages.qrcode)
(pythonPackages.tf-nightly)
(pythonPackages.yamllint)
(pythonPackages.sendgrid)
# (pythonPackages.oslotest)
(pythonPackages.datetime)
(pythonPackages.html2text)
## (pythonPackages.flask-admin)
# (pythonPackages.django-mptt)
(pythonPackages.annoy)
(pythonPackages.pg8000)
(pythonPackages.progressbar2)
(pythonPackages.stestr)
(pythonPackages.py2-ipaddress)
(pythonPackages.pyathenajdbc)
(pythonPackages.cairocffi)
# (pythonPackages.oslo-service)
(pythonPackages.codeintel)
(pythonPackages.clr)
(pythonPackages.ssh)
(pythonPackages.nose-cov)
(pythonPackages.bintrees)
(pythonPackages.toml)
# (pythonPackages.djangorestframework-jwt)
(pythonPackages.uritemplate-py)
(pythonPackages.awacs)
(pythonPackages.sirepo)
(pythonPackages.pyes)
(pythonPackages.pygame)
(pythonPackages.reno)
(pythonPackages.python-utils)
# (pythonPackages.oslo-policy)
(pythonPackages.lmdb)
(pythonPackages.profilehooks)
(pythonPackages.pydot)
(pythonPackages.logutils)
# (pythonPackages.django-allauth)
(pythonPackages.pyvmomi)
(pythonPackages.cairosvg)
(pythonPackages.jenkinsapi)
(pythonPackages.pypng)
(pythonPackages.azure-mgmt-web)
(pythonPackages.openapi-codec)
(pythonPackages.wordsegment)
## (pythonPackages.flask-mail)
(pythonPackages.pulp)
(pythonPackages.backport-collections)
(pythonPackages.pyramid)
(pythonPackages.python-logstash)
(pythonPackages.dateutils)
(pythonPackages.dropbox)
(pythonPackages.gsutil)
(pythonPackages.pre-commit)
(pythonPackages.python3-openid)
(pythonPackages.rjsmin)
(pythonPackages.line-profiler)
(pythonPackages.pep8-naming)
(pythonPackages.pygithub)
(pythonPackages.pyinstaller)
(pythonPackages.rq)
(pythonPackages.dictdiffer)
(pythonPackages.azure-mgmt-sql)
(pythonPackages.recommonmark)
(pythonPackages.azure-mgmt-cdn)
(pythonPackages.apache-libcloud)
(pythonPackages.mongoengine)
(pythonPackages.azure-mgmt-authorization)
(pythonPackages.clickclick)
(pythonPackages.haigha)
(pythonPackages.schematics)
(pythonPackages.initools)
(pythonPackages.txaio)
(pythonPackages.pysubnettree)
(pythonPackages.translationstring)
(pythonPackages.shade)
(pythonPackages.tablib)
(pythonPackages.pypandoc)
(pythonPackages.flufl-enum)
(pythonPackages.pyusb)
(pythonPackages.delorean)
(pythonPackages.tifffile)
(pythonPackages.udatetime)
(pythonPackages.rcssmin)
# (pythonPackages.typed-ast)
(pythonPackages.azure-mgmt-dns)
(pythonPackages.py-zabbix)
(pythonPackages.pysnmp)
(pythonPackages.azure-mgmt-cognitiveservices)
(pythonPackages.azure-graphrbac)
(pythonPackages.flake8-docstrings)
(pythonPackages.jellyfish)
(pythonPackages.fluent-logger)
(pythonPackages.azure-mgmt-scheduler)
(pythonPackages.requesocks)
(pythonPackages.simple-salesforce)
(pythonPackages.multiprocess)
# (pythonPackages.django-environ)
(pythonPackages.azure-datalake-store)
(pythonPackages.azure-mgmt-containerregistry)
(pythonPackages.apsw)
(pythonPackages.cloudpickle)
(pythonPackages.publicsuffix)
(pythonPackages.sure)
(pythonPackages.shellescape)
(pythonPackages.github3-py)
(pythonPackages.mypy)
(pythonPackages.backoff)
(pythonPackages.filelock)
(pythonPackages.azure-mgmt-datalake-store)
# (pythonPackages.oslosphinx)
(pythonPackages.venusian)
(pythonPackages.azure-mgmt-datalake-analytics)
(pythonPackages.azure-mgmt-iothub)
# (pythonPackages.ftfy)
(pythonPackages.watchtower)
(pythonPackages.pytestcache)
(pythonPackages.psycogreen)
(pythonPackages.pyotp)
(pythonPackages.python-cdb)
# (pythonPackages.django-oauth-toolkit)
(pythonPackages.azure-mgmt-documentdb)
(pythonPackages.azure-keyvault)
(pythonPackages.pyhs2)
(pythonPackages.kubernetes)
(pythonPackages.azure-mgmt-devtestlabs)
(pythonPackages.bandit)
(pythonPackages.memory-profiler)
(pythonPackages.luigi)
(pythonPackages.azure-mgmt-rdbms)
(pythonPackages.azure-mgmt-datalake-nspkg)
(pythonPackages.tempora)
(pythonPackages.python2-pythondialog)
(pythonPackages.pylibmc)
(pythonPackages.azure-mgmt-logic)
(pythonPackages.polib)
(pythonPackages.cchardet)
(pythonPackages.pycryptodomex)
(pythonPackages.pep257)
(pythonPackages.dedupe)
(pythonPackages.requests-kerberos)
(pythonPackages.pika-pool)
(pythonPackages.sqlalchemy-redshift)
(pythonPackages.jenkins-job-builder)
(pythonPackages.python-http-client)
(pythonPackages.cheroot)
# (pythonPackages.livereload)
(pythonPackages.backports_lzma)
(pythonPackages.gecosistema-lite)
(pythonPackages.plac)
(pythonPackages.google)
(pythonPackages.pytsite)
(pythonPackages.azure-mgmt-common)
(pythonPackages.yapf)
# (pythonPackages.django-countries)
(pythonPackages.cerberus)
# (pythonPackages.pycadf)
# (pythonPackages.django-taggit)
# (pythonPackages.django-redis-cache)
(pythonPackages.urwid)
(pythonPackages.webcolors)
(pythonPackages.python-crfsuite)
(pythonPackages.pyroute2)
(pythonPackages.aspy-yaml)
(pythonPackages.pefile)
(pythonPackages.ciso8601)
(pythonPackages.pykerberos)
# (pythonPackages.django-widget-tweaks)
(pythonPackages.pytestcatchlog)
(pythonPackages.deepdiff)
(pythonPackages.hvac)
(pythonPackages.phonenumberslite)
(pythonPackages.salt)
(pythonPackages.parsley)
(pythonPackages.swagger-spec-validator)
## (pythonPackages.flask-swagger)
(pythonPackages.google-apitools)
# (pythonPackages.oslo-versionedobjects)
# (pythonPackages.keystonemiddleware)
(pythonPackages.repoze-who)
(pythonPackages.thinc)
(pythonPackages.scapy)
(pythonPackages.public)
(pythonPackages.bashate)
(pythonPackages.structlog)
(pythonPackages.nose-exclude)
(pythonPackages.automaton)
(pythonPackages.atx)
(pythonPackages.tox-travis)
# (pythonPackages.django-formtools)
(pythonPackages.cvxopt)
# (pythonPackages.taskflow)
(pythonPackages.impyla)
(pythonPackages.pylint-plugin-utils)
(pythonPackages.rollbar)
(pythonPackages.murmurhash)
(pythonPackages.identify)
# (pythonPackages.oslo-reports)
(pythonPackages.googlemaps)
(pythonPackages.naked)
(pythonPackages.python-designateclient)
(pythonPackages.portend)
(pythonPackages.geocoder)
(pythonPackages.boxsdk)
(pythonPackages.premailer)
(pythonPackages.pecan)
(pythonPackages.pygeoip)
## (pythonPackages.flask-testing)
(pythonPackages.python-snappy)
(pythonPackages.cymem)
# (pythonPackages.spacy)
# (pythonPackages.oslo-rootwrap)
(pythonPackages.flake8-polyfill)
(pythonPackages.wavefront-cli)
(pythonPackages.wincertstore)
(pythonPackages.pybars3)
(pythonPackages.pypdf)
(pythonPackages.netius)
(pythonPackages.pymeta3)
(pythonPackages.netdisco)
## (pythonPackages.flask-babel)
(pythonPackages.tblib)
# (pythonPackages.django-picklefield)
(pythonPackages.preshed)
(pythonPackages.neutron-lib)
(pythonPackages.cytoolz)
(pythonPackages.diff-match-patch)
(pythonPackages.edx-enterprise)
# (pythonPackages.django-reversion)
(pythonPackages.zeroconf)
(pythonPackages.setupfiles)
(pythonPackages.get)
(pythonPackages.shadowsocks)
(pythonPackages.logging)
(pythonPackages.request)
(pythonPackages.pysmi)
(pythonPackages.shutit)
(pythonPackages.attrdict)
(pythonPackages.eggtestinfo)
(pythonPackages.validators)
# (pythonPackages.django-localflavor)
(pythonPackages.coloredlogs)
(pythonPackages.tooz)
(pythonPackages.post)
(pythonPackages.robotframework-selenium2library)
(pythonPackages.credstash)
(pythonPackages.grequests)
(pythonPackages.semver)
(pythonPackages.logbook)
(pythonPackages.connexion)
(pythonPackages.osprofiler)
(pythonPackages.rauth)
(pythonPackages.query-string)
(pythonPackages.jsmin)
(pythonPackages.pysaml2)
(pythonPackages.azure-servicefabric)
(pythonPackages.xattr)
(pythonPackages.flaky)
(pythonPackages.glances)
(pythonPackages.okpy)
# (pythonPackages.django-haystack)
# (pythonPackages.easy-thumbnails)
(pythonPackages.btrees)
]